#!/bin/sh
# Stamp date-based version: YY.M.D (HH.MM)
# Runs in Xcode Cloud after cloning, before build.
set -eu

repo_path="${CI_PRIMARY_REPOSITORY_PATH:-$(cd "$(dirname "$0")/.." && pwd)}"
config_path="$repo_path/Config/Identifiers.local.xcconfig"

write_if_present() {
    key="$1"
    value="${2:-}"
    if [ -n "$value" ]; then
        printf '%s = %s\n' "$key" "$value" >> "$config_path"
    fi
}

# Recreate the local Xcode override file in CI from environment variables.
# This keeps tracked config portable while giving Xcode Cloud the real team
# and bundle identifier needed for archive signing.
: "${ELEVATED_APPLE_TEAM_ID:?Missing ELEVATED_APPLE_TEAM_ID in CI environment}"
: "${ELEVATED_APP_IDENTIFIER:?Missing ELEVATED_APP_IDENTIFIER in CI environment}"

: > "$config_path"
printf '// Generated by ci_scripts/ci_post_clone.sh\n' >> "$config_path"

write_if_present ELEVATED_APPLE_TEAM_ID "${ELEVATED_APPLE_TEAM_ID:-}"
write_if_present ELEVATED_APP_IDENTIFIER "${ELEVATED_APP_IDENTIFIER:-}"

metal_sdk=macosx
case "${CI_PRODUCT_PLATFORM:-}" in
    iOS) metal_sdk=iphoneos ;;
    tvOS) metal_sdk=appletvos ;;
    visionOS) metal_sdk=xros ;;
esac

metal_toolchain_ready() {
    xcrun metal -v >/dev/null 2>&1 &&
        xcrun --sdk "$metal_sdk" metal -v >/dev/null 2>&1
}

ensure_metal_toolchain() {
    if metal_toolchain_ready; then
        echo "Metal Toolchain already available for ${CI_PRODUCT_PLATFORM:-macOS}."
        return
    fi

    echo "Downloading Metal Toolchain for ${CI_PRODUCT_PLATFORM:-macOS}..."
    xcodebuild -downloadComponent MetalToolchain || true

    # Xcode Cloud can report the asset as imported but still fail later unless
    # the toolchain lookup is refreshed and verified immediately.
    xcrun -k >/dev/null 2>&1 || true

    if metal_toolchain_ready; then
        echo "Metal Toolchain ready."
        return
    fi

    echo "Metal Toolchain is unavailable after download/import." >&2
    exit 1
}

ensure_metal_toolchain

"$repo_path/stamp-version.sh"

# Run Swift package tests (macOS only — swift test can't cross-compile)
if [ "${CI_XCODEBUILD_ACTION:-}" = "" ] || [ "${CI_PRODUCT_PLATFORM:-}" = "macOS" ]; then
    echo "Running swift test..."
    cd "$repo_path/elevated"
    swift test 2>&1
    echo "Tests passed."
else
    echo "Skipping swift test on ${CI_PRODUCT_PLATFORM:-unknown} (macOS only)."
fi
