#!/bin/sh
# Stamp date-based version: YY.M.D (HH.MM)
# Runs in Xcode Cloud after cloning, before build.
set -eu

repo_path="${CI_PRIMARY_REPOSITORY_PATH:-$(cd "$(dirname "$0")/.." && pwd)}"
config_path="$repo_path/Config/Identifiers.local.xcconfig"

write_if_present() {
    key="$1"
    value="${2:-}"
    if [ -n "$value" ]; then
        printf '%s = %s\n' "$key" "$value" >> "$config_path"
    fi
}

# Recreate the local Xcode override file in CI from environment variables.
# This keeps tracked config portable while giving Xcode Cloud the real team
# and bundle identifiers needed for archive signing.
: "${ELEVATED_IOS_TEAM_ID:?Missing ELEVATED_IOS_TEAM_ID in CI environment}"
: "${ELEVATED_IOS_APP_IDENTIFIER:?Missing ELEVATED_IOS_APP_IDENTIFIER in CI environment}"

: > "$config_path"
printf '// Generated by ci_scripts/ci_post_clone.sh\n' >> "$config_path"

write_if_present ELEVATED_IOS_TEAM_ID "${ELEVATED_IOS_TEAM_ID:-}"
write_if_present ELEVATED_TVOS_TEAM_ID "${ELEVATED_TVOS_TEAM_ID:-}"
write_if_present ELEVATED_VISIONOS_TEAM_ID "${ELEVATED_VISIONOS_TEAM_ID:-}"

write_if_present ELEVATED_IOS_APP_IDENTIFIER "${ELEVATED_IOS_APP_IDENTIFIER:-}"
write_if_present ELEVATED_TVOS_APP_IDENTIFIER "${ELEVATED_TVOS_APP_IDENTIFIER:-}"
write_if_present ELEVATED_VISIONOS_APP_IDENTIFIER "${ELEVATED_VISIONOS_APP_IDENTIFIER:-}"

exec "$repo_path/stamp-version.sh"
