#!/bin/sh
# Stamp date-based version: YY.M.D (HH.MM)
# Runs in Xcode Cloud after cloning, before build.
set -eu

repo_path="${CI_PRIMARY_REPOSITORY_PATH:-$(cd "$(dirname "$0")/.." && pwd)}"
config_path="$repo_path/Config/Identifiers.local.xcconfig"

write_if_present() {
    key="$1"
    value="${2:-}"
    if [ -n "$value" ]; then
        printf '%s = %s\n' "$key" "$value" >> "$config_path"
    fi
}

# Recreate the local Xcode override file in CI from environment variables.
# This keeps tracked config portable while giving Xcode Cloud the real team
# and bundle identifier needed for archive signing.
: "${ELEVATED_APPLE_TEAM_ID:?Missing ELEVATED_APPLE_TEAM_ID in CI environment}"
: "${ELEVATED_APP_IDENTIFIER:?Missing ELEVATED_APP_IDENTIFIER in CI environment}"

: > "$config_path"
printf '// Generated by ci_scripts/ci_post_clone.sh\n' >> "$config_path"

write_if_present ELEVATED_APPLE_TEAM_ID "${ELEVATED_APPLE_TEAM_ID:-}"
write_if_present ELEVATED_APP_IDENTIFIER "${ELEVATED_APP_IDENTIFIER:-}"

# Ensure Metal toolchain is available (required for .metal shader compilation in Xcode 26+)
echo "Installing Metal Toolchain..."
xcodebuild -downloadComponent MetalToolchain || true

"$repo_path/stamp-version.sh"

# Run Swift package tests (macOS only — swift test can't cross-compile)
if [ "${CI_XCODEBUILD_ACTION:-}" = "" ] || [ "${CI_PRODUCT_PLATFORM:-}" = "macOS" ]; then
    echo "Running swift test..."
    cd "$repo_path/elevated"
    swift test 2>&1
    echo "Tests passed."
else
    echo "Skipping swift test on ${CI_PRODUCT_PLATFORM:-unknown} (macOS only)."
fi
