#!/usr/bin/env python3
"""Pack the CSynth music tables into a compact zero-run/literal stream."""

from __future__ import annotations

import ast
import re
import sys
from pathlib import Path


TABLES = [
    ("pattern_data", "PATTERN_DATA_LEN", "kPatternDataPacked"),
    ("sequence_data", "SEQUENCE_DATA_LEN", "kSequenceDataPacked"),
    ("machine_tree_data", "MACHINE_TREE_DATA_LEN", "kMachineTreeDataPacked"),
]


def parse_arrays(source: str) -> dict[str, list[int]]:
    arrays: dict[str, list[int]] = {}
    for name, _, _ in TABLES:
        match = re.search(
            rf"static const uint8_t {name}\[\]\s*=\s*\{{(.*?)\}};",
            source,
            re.S,
        )
        if not match:
            raise SystemExit(f"missing table: {name}")
        arrays[name] = ast.literal_eval("[" + match.group(1).replace("\n", " ") + "]")
    return arrays


def pack_zero_rle(values: list[int]) -> list[int]:
    packed: list[int] = []
    i = 0
    while i < len(values):
        if values[i] == 0:
            j = i
            while j < len(values) and values[j] == 0 and j - i < 128:
                j += 1
            packed.append(0x80 | (j - i - 1))
            i = j
            continue

        j = i
        while j < len(values) and j - i < 128:
            if values[j] == 0 and j + 1 < len(values) and values[j + 1] == 0:
                break
            j += 1
        packed.append(j - i - 1)
        packed.extend(values[i:j])
        i = j

    return packed


def format_bytes(values: list[int]) -> str:
    rows = []
    for i in range(0, len(values), 16):
        chunk = values[i : i + 16]
        rows.append("    " + ",".join(str(v) for v in chunk) + ",")
    return "\n".join(rows)


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: pack_synth_tables.py <raw-header> <packed-header>", file=sys.stderr)
        return 2

    src = Path(sys.argv[1])
    dst = Path(sys.argv[2])
    arrays = parse_arrays(src.read_text())

    lines = [
        "#pragma once",
        "#include <stdint.h>",
        "",
        "/* Auto-generated by elevated4k/pack_synth_tables.py. Do not edit. */",
        "/* Format: high bit set => run of zeros, otherwise literal run; low 7 bits store count-1. */",
        "",
    ]

    for raw_name, len_name, packed_name in TABLES:
        raw = arrays[raw_name]
        packed = pack_zero_rle(raw)
        savings = len(raw) - len(packed)
        lines.append(f"#define {len_name} {len(raw)}")
        lines.append(
            f"/* {raw_name}: {len(raw)} -> {len(packed)} bytes ({savings} bytes saved) */"
        )
        lines.append(f"static const uint8_t {packed_name}[] = {{")
        lines.append(format_bytes(packed))
        lines.append("};")
        lines.append("")

    dst.write_text("\n".join(lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
