// shaders.h — auto-generated from Shaders.metal, do not edit
// Regenerate with: make shaders

static const char kMSLSource[] =
    "#include <metal_stdlib>\n"
    "using namespace metal;\n"
    "struct U{\n"
    "float4 q[16];\n"
    "float4x4 v;\n"
    "float4x4 vi;\n"
    "float2 resolution;\n"
    "float time;\n"
    "float _pad;\n"
    "};\n"
    "struct O{\n"
    "float4 w[[color(0)]];\n"
    "};\n"
    "struct V{\n"
    "float4 p[[position]];\n"
    "float4 w;\n"
    "};\n"
    "struct P{\n"
    "float4 p[[position]];\n"
    "float2 u;\n"
    "};\n"
    "float3 no(float2 p,texture2d<float>t0,sampler s0){\n"
    "float2 f=fract(p);\n"
    "float2 u=f*f*f*(f*(f*6-15)+10);\n"
    "float a=t0.sample(s0,(floor(p)+float2(0,0))/256,level(0)).r;\n"
    "float b=t0.sample(s0,(floor(p)+float2(1,0))/256,level(0)).r;\n"
    "float c=t0.sample(s0,(floor(p)+float2(0,1))/256,level(0)).r;\n"
    "float d=t0.sample(s0,(floor(p)+float2(1,1))/256,level(0)).r;\n"
    "return float3(\n"
    "a+(b-a)*u.x+(c-a)*u.y+(a-b-c+d)*u.x*u.y,\n"
    "30*f*f*(f*(f-2)+1)*(float2(b-a,c-a)+(a-b-c+d)*u.yx)\n"
    ");\n"
    "}\n"
    "float fbm(float2 p,float o,texture2d<float>t0,sampler s0){\n"
    "float2 d=0;\n"
    "float a=0;\n"
    "float bv=3;\n"
    "for(float i=0;i<o;i++){\n"
    "float3 n=no(0.25*p,t0,s0);\n"
    "d +=n.yz;\n"
    "a +=(bv*=0.5)*n.x/(1 + dot(d,d));\n"
    "p=float2x2(1.6,1.2,-1.2,1.6)*p;\n"
    "}\n"
    "return a;\n"
    "}\n"
    "float3 cn(float2 p,float e,float o,constant U& u,\n"
    "texture2d<float>t0,sampler s0){\n"
    "float a=fbm(p,o,t0,s0);\n"
    "return normalize(float3(\n"
    "u.q[2].w*(a - fbm(p+float2(e,0),o,t0,s0)),\n"
    "e,\n"
    "u.q[2].w*(a - fbm(p+float2(0,e),o,t0,s0))\n"
    "));\n"
    "}\n"
    "float3 sl(float3 p,float3 c,float3 d,constant U& u,\n"
    "texture2d<float>t0,sampler s0){\n"
    "float a=dot(d,u.q[3].xyz);\n"
    "float bv=mix(a,dot(c,u.q[3].xyz),0.5 + 0.5*u.q[2].x);\n"
    "return float3(.13,.18,.22)*(c.y + 0.25*saturate(-bv)- 0.1*no(1024*p.xz,t0,s0).y)\n"
    "+ float3(1.4,1,.7)*saturate(bv)*saturate(2*a);\n"
    "}\n"
    "vertex V a(\n"
    "uint i[[vertex_id]],\n"
    "constant float2*p[[buffer(0)]],\n"
    "constant U& u[[buffer(1)]],\n"
    "texture2d<float>t0[[texture(0)]])\n"
    "{\n"
    "constexpr sampler s0(address::repeat,filter::nearest);\n"
    "float2 xz=p[i];\n"
    "float h=u.q[2].w*fbm(xz,8,t0,s0);\n"
    "float4 w=float4(xz.x,h,xz.y,1);\n"
    "V r;\n"
    "r.w=w;\n"
    "r.p=u.v*w;\n"
    "return r;\n"
    "}\n"
    "fragment O b(V i[[stage_in]]){\n"
    "O r;\n"
    "r.w=float4(i.w.xyz,1.0);\n"
    "return r;\n"
    "}\n"
    "vertex P c(uint i[[vertex_id]]){\n"
    "float2 pos[3]={float2(-1,-1),float2(3,-1),float2(-1,3)};\n"
    "float2 uv[3]={float2(0,1),float2(2,1),float2(0,-1)};\n"
    "P r;\n"
    "r.p=float4(pos[i],0,1);\n"
    "r.u=uv[i];\n"
    "return r;\n"
    "}\n"
    "fragment float4 d(\n"
    "P i[[stage_in]],\n"
    "constant U& u[[buffer(0)]],\n"
    "texture2d<float>t0[[texture(0)]],\n"
    "texture2d<float>t1[[texture(1)]])\n"
    "{\n"
    "constexpr sampler s0(address::repeat,filter::nearest);\n"
    "constexpr sampler s1(address::clamp_to_edge,filter::linear);\n"
    "float2 x=i.u;\n"
    "float2 o=x + 0.5/1280;\n"
    "float4 d=t1.sample(s1,o);\n"
    "float4 eye4=u.vi*float4(x.x*2-1,1-x.y*2,1,1);\n"
    "float3 e=normalize(eye4.xyz);\n"
    "float ey=(abs(e.y)<0.001)?((e.y<0.0)?-0.001:0.001):e.y;\n"
    "float2 s=e.xz/ey;\n"
    "float k=fmod(2*s.y + 1000,8);\n"
    "float3 c=float3(.55,.65,.75)\n"
    "+ 0.1*fbm(s + u.q[3].w*0.2,10,t0,s0)\n"
    "+ 0.5*pow(1-ey,8)\n"
    "+ pow(saturate(dot(e,u.q[3].xyz)),16)*float3(.4,.3,.1)\n"
    "+ float4(1+0.4*k,2,3+0.5*k,0).xyz\n"
    "*(1 - cos(12.5664*s.y))\n"
    "*saturate(1 - abs(s.y)/10 - abs(s.x + u.q[5+(int)k].x*0.0012 - 8)/20)\n"
    "*exp(-u.q[5+(int)k].x*0.0002);\n"
    "if(d.w>0.5){\n"
    "float t=length(d.xyz - u.q[4].xyz);\n"
    "float w=u.q[1].w - d.y;\n"
    "if(w<0){\n"
    "float3 n=cn(d.xz,0.001*t,12 - log2(t),u,t0,s0);\n"
    "float h=fbm(3*d.xz,3,t0,s0);\n"
    "float r=no(666*d.xz,t0,s0).x;\n"
    "c=(0.1 + 0.75*u.q[2].x)*(0.8 + 0.2*r);\n"
    "c=mix(c,\n"
    "mix(float3(.8,.85,.9),float3(.45,.45,.2)*(0.8+0.2*r),u.q[2].x),\n"
    "smoothstep(0.5 - 0.8*n.y,1 - 1.1*n.y,h*0.15));\n"
    "c=mix(c,\n"
    "mix(float3(.37,.23,.08),float3(.42,.4,.2),u.q[2].x)*(0.5+0.5*r),\n"
    "smoothstep(0,1,50*(n.y-1)+(h+u.q[2].x)/0.4));\n"
    "c*=sl(d.xyz,n,cn(d.xz,0.001*t,5,u,t0,s0),u,t0,s0);\n"
    "}else{\n"
    "t=(u.q[1].w - u.q[4].y)/e.y;\n"
    "d.xyz=u.q[4].xyz + e*t;\n"
    "float2 wXZ=d.xz;\n"
    "float3 n=normalize(cn(float2(512,32)*wXZ\n"
    "+ saturate(w*60)*float2(u.q[3].w,0),\n"
    "0.001*t,4,u,t0,s0)*float3(1,6,1));\n"
    "c=0.12*(float3(.4,1,1)- float3(.2,.6,.4)*saturate(w*16));\n"
    "c*=0.3 + 0.7*u.q[2].x;\n"
    "c +=pow(1 - dot(-e,n),4)\n"
    "*(pow(saturate(dot(u.q[3].xyz,reflect(-e,n))),32)*float3(.32,.31,.3)+ 0.1);\n"
    "c=mix(c,\n"
    "sl(d.xyz,n,n,u,t0,s0),\n"
    "smoothstep(1,0,\n"
    "u.q[2].x + w*60\n"
    "- fbm(666*wXZ + saturate(w*60)*float2(u.q[3].w,0)*2,5,t0,s0))*0.5);\n"
    "}\n"
    "c*=0.7 + 0.3*smoothstep(0,1,256*abs(w));\n"
    "c*=exp(-0.042*t);\n"
    "c +=(1 - exp(-0.1*t))\n"
    "*(float3(.52,.59,.65)+ pow(saturate(dot(e,u.q[3].xyz)),8)*float3(.6,.4,.1));\n"
    "}\n"
    "return float4(c,0);\n"
    "}\n"
    "fragment float4 e(\n"
    "P i[[stage_in]],\n"
    "constant U& u[[buffer(0)]],\n"
    "texture2d<float>t0[[texture(0)]],\n"
    "texture2d<float>t1[[texture(1)]],\n"
    "texture2d<float>t2[[texture(2)]])\n"
    "{\n"
    "constexpr sampler s0(address::repeat,filter::nearest);\n"
    "constexpr sampler s1(address::clamp_to_edge,filter::linear);\n"
    "float2 o=i.u + 0.5/1280;\n"
    "float4 d=t1.sample(s1,o);\n"
    "float3 c=t2.sample(s1,o).rgb;\n"
    "if(d.w>0.5){\n"
    "float4 clip=u.v*float4(d.xyz,1);\n"
    "clip.y*=-1;\n"
    "c=0;\n"
    "for(float i=0;i<16;i++){\n"
    "c.x +=t2.sample(s1,o + i*(0.5 + 0.5*clip.xy/clip.w - o)/16 + float2(2,0)/1280).r;\n"
    "c.y +=t2.sample(s1,o + i*(0.5 + 0.5*clip.xy/clip.w - o)/16 + float2(0,0)/1280).g;\n"
    "c.z +=t2.sample(s1,o + i*(0.5 + 0.5*clip.xy/clip.w - o)/16 + float2(-2,0)/1280).b;\n"
    "}\n"
    "c/=16;\n"
    "}\n"
    "c=pow(c,0.45)*u.q[2].z + u.q[2].y;\n"
    "c*=0.4 + 9.6*o.x*o.y*(1-o.x)*(1-o.y);\n"
    "c.xz*=0.98;\n"
    "float w=t0.sample(s0,u.q[3].w*0.1).r;\n"
    "o +=w;\n"
    "c -=0.005*w;\n"
    "c.x +=0.01*t0.sample(s0,o + float2(0.1,0)).r;\n"
    "c.y +=0.01*t0.sample(s0,o + float2(0.2,0)).r;\n"
    "c.z +=0.01*t0.sample(s0,o + float2(0.3,0)).r;\n"
    "return float4(c,0);\n"
    "}\n"
    ;
